---
version: 2.1

jobs:
  test:
    parameters:
      ruby_image:
        type: string

    docker:
    - image: << parameters.ruby_image >>

    steps:
    - checkout
    # JRuby <= 9.2.x is no longer supported by the `rubygems-update` gem, which now
    # requires at least Ruby 2.6 compatibility.
    #
    # For now, we'll pin to the last supported version. We can drop this check once we
    # drop all those versions of JRuby.
    - run: |
        running_old_ruby=$(ruby -e 'puts Gem::Version.new(RUBY_VERSION) < Gem::Version.new("2.6.0")')
        if [[ "${running_old_ruby}" == "true" ]]; then 
          gem update --system 3.3.26
        else
          gem update --system
        fi
    - run: bundle install
    - run: bundle exec rake

workflows:
  version: 2
  client_ruby:
    jobs:
    - test:
        matrix:
          parameters:
            ruby_image:
            - cimg/ruby:2.6
            - cimg/ruby:2.7
            - cimg/ruby:3.0
            - cimg/ruby:3.1
            - circleci/jruby:9.1
            - circleci/jruby:9.2
            - circleci/jruby:9.3
